### ISSUE TITLE
страница /addDepartment, дропдаун 

### ISSUE THREAD

**Issue by jurStv** [jurStv/kraj_adm#1]
Нужно чтоб была возможность выбирать несколько вариантов (посмотреть в бутстрапе компоненты для множественного выбора); возможно dropdown совмещенный с checkbox + изначально инпут (т.е. изначально возможность ввести вручную + выпадает дропдаун с чекбоксами)

**Comment by jurStv** [comment]
+ при выборе варианта, добавляется внизу этот вариант с крестиком, как лэйбл =)

**Comment by sasha-kazakevich** [comment]
сделал.варианты добовляются внутри инпута

**Comment by jurStv** [comment]
ништяк!
