### ISSUE TITLE
страница /departmentsOrder

### ISSUE THREAD

**Issue by jurStv** [jurStv/kraj_adm#3]
убрать кнопки "Вверх" и "Вниз" вместо них менять порядок мышой драг н дроп + продумать чтоб на мобиле это тоже работало
есть такой плагин jQuery UI, plugin sort - что-то похожее надо и тут, возможно в AdminLTE уже есть такая штука

**Comment by sasha-kazakevich** [comment]
сделал. использовал самое просто решение какое нашел.на мобиле должно работать как пишут,но если что есть другой вариант решения http://dbushell.github.io/Nestable/ там все посложнее и нужно использовать обязательно списки

**Comment by jurStv** [comment]
подглючивает - посмотри, когда берешь самый последний элемент и перетягиваешь его в самый вверх появляется пространство между мышой и элементом

**Comment by sasha-kazakevich** [comment]
поправил баг. тестировал по всякому пространство не появлялось. еще нашел один плагин там все работает четка и наверняка но он намного проще по анимации нет наслоения как тут.если что можно воспользоваться им
