### ISSUE TITLE
резина

### ISSUE THREAD

**Issue by jurStv** [jurStv/kraj_adm#8]
перепроверить все нормально ли под мобилу смотрится

**Comment by sasha-kazakevich** [comment]
все блоки подправил под мобилу. в  блоке addNews старался оставить первоначальный вид до момента перехода к классу .col-хs после расширил все импуты и селекты на всю длину. на расширении 320px смотрится не плохо

**Comment by jurStv** [comment]
осталось по таблицам комментариев определиться. как они будут вести себя на мобиле. пока что просто скролл горизонтальный появляется и походу это самое адекватное что можно придумать
